config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  get "/teams" => 'home#teams', as: :teams
  get "/leagues" => 'home#leagues', as: :leagues
  get "/players" => 'home#players', as: :players
  get "/stadiums" => 'home#stadiums', as: :stadiums
  post "/create_comment"=> 'home#create_comment', as: :create_comment
  get "/delete_comment"=> 'home#delete_comment', as: :delete_comment
  post "/update_comment"=> 'home#update_comment', as: :update_comment
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :stadium
end

app/models/competition.rb
class Competition

  # def self.api_path
  #   "/v1/competitions/"
  # end

  # def self.fetch_all
  #   response = RestClient.get("#{BASE_URL}#{api_path}")
  #   JSON.parse(response.body)
  # end

  # def self.get_teams(competition_id)
  #   response = RestClient.get("#{BASE_URL}/v1/competitions/#{competition_id}/teams")
  #   JSON.parse(response.body)["teams"]
  # end

  # def self.get_league_tables(competition_id)
  #   response = RestClient.get("#{BASE_URL}/v1/competitions/#{competition_id}/leagueTable")
  #   JSON.parse(response.body)
  # end

  # def self.get_team_data(team_id)
  #   response = RestClient.get("#{BASE_URL}/v1/competitions/#{competition_id}/leagueTable")
  #   JSON.parse(response.body)
  # end

  # def self.get_players(team_id)
  #   response = RestClient.get("#{BASE_URL}/v1/teams/#{team_id}/players")
  #   JSON.parse(response.body)
  # end

  def self.fetch_all
    FootballData.fetch(:competitions)
  end

  def self.get_teams(competition_id)
    FootballData.fetch(:competitions, :teams, id: competition_id)["teams"]
  end

  def self.get_league_tables(competition_id)
    FootballData.fetch(:competitions, :leagueTable, id: competition_id)
  end

  def self.get_team_data(team_id)
    FootballData.fetch(:teams, nil, id: team_id)
  end

  def self.get_players(team_id)
    FootballData.fetch(:teams, :players, id: team_id)["players"]
  end

end

app/models/stadium.rb
class Stadium < ApplicationRecord
  self.table_name = "stadiums"
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @all_competitions = Competition.fetch_all
  end

  def leagues
    @league_table = Competition.get_league_tables(params[:competition_id])
  end

  def teams
    @stadiums = Stadium.all
    @teams = Competition.get_teams(params[:competition_id])
  end

  def players
    @players = Competition.get_players(params[:team_id])
  end

  def stadiums
    @stadium = Stadium.find params[:stadium_id]
    query = "#{@stadium.state},#{@stadium.country}"
    api_key = "451864d3f1b8f323eb7e31b514e45831"
    f = Faraday.new(url: "http://api.openweathermap.org/data/2.5/find?q=#{query}&units=imperial&appid=#{api_key}")
    @weather_data = JSON.parse(f.get.body)["list"][0]
    @comments = @stadium.comments.order("created_at DESC")
  end

  def create_comment
    @comment = Comment.new(body: params[:body],stadium_id: params[:stadium_id])
    @comment.save
    @comments = Comment.where(stadium_id: params[:stadium_id]).order("created_at DESC")
  end


  def update_comment
    @comment = Comment.find(params[:comment_id])
    @comment.update_attributes(body: params[:body])
    @comments = Comment.where(stadium_id: @comment.stadium_id).order("created_at DESC")
  end

  def delete_comment
    @comment = Comment.find(params[:comment_id]).destroy
    @comments = Comment.where(stadium_id: @comment.stadium_id).order("created_at DESC")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/_index.html.erb
<% if comments.any? %>
  <table class="table">
    <tbody>
      <% comments.each do |comment| %>
        <tr>
          <td><%= comment.body %></td>
          <td>
            <%= link_to "Edit", "javascript:void(0)",onclick: "document.getElementById('comment_form_#{comment.id}').style = 'display:block;'" %>

            <form id="comment_form_<%= comment.id %>" data-remote="true" action="<%= update_comment_path(comment_id: comment.id) %>" method="post" style="display:none;">
              <input type="hidden" name="comment_id" value=<%= comment.id %> >
              <textarea placeholder="Write a comment" name="body"><%= comment.body %></textarea>
              </br>
              <input type="submit" value="Update comment">
            </form>            
          </td>

          <td><%= link_to "Delete", delete_comment_path(comment_id: comment.id), remote: true %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <label>No Comments Yet</label>
<% end %>

app/views/home/create_comment.js.erb
<% if @comment.errors.any? %>
  alert("Problem creating comment.")  
<% else %>
  document.getElementById("comment_form").reset()
  document.getElementById("comments").innerHTML = "<%=j render 'comments/index',comments: @comments %>"
  // $("#comments").html("<%=j render 'comments/index',comments: @comments %>")
<% end %>

app/views/home/delete_comment.js.erb
<% if @comment.errors.any? %>
  alert("Problem creating comment.")  
<% else %>
  document.getElementById("comment_form").reset()
  document.getElementById("comments").innerHTML = "<%=j render 'comments/index',comments: @comments %>"
<% end %>

app/views/home/index.html.erb
<h1>List of All Competition</h1>

<%= react_component("Competition", competitions: @all_competitions) %>

app/views/home/leagues.html.erb
| <%= link_to "Back", :back %>


<h1>League Detail</h1>
<lable>League Caption : <%= @league_table["leagueCaption"]%></lable>
</br>
<lable>Matchday : <%= @league_table["matchday"]%></lable>
<h4>Standings</h4>

<%= react_component("League", standing: @league_table["standing"]) %>

app/views/home/players.html.erb
| <%= link_to "Back", :back %>

<h1>List of All Players</h1>
<%= react_component("Player", players: @players) %>

app/views/home/stadiums.html.erb
<div style="text-align: center;">
  <%= react_component("Stadium", stadium: @stadium,image_path: asset_path(@stadium.image) , weather: @weather_data) %>

  <form id="comment_form" action="/create_comment" method="POST" data-remote=true>
    <input type="hidden" name="stadium_id" value="<%= @stadium.id %>">
    <textarea placeholder="Write a comment" name="body"></textarea>
    </br>
    <input type="submit" value="Add comment">
  </form>
  <h3>Comments</h3>
  <div id="comments" style="max-height: 300px;overflow-y: scroll;">
    <%= render "comments/index", comments: @comments %>
  </div>

</div>

app/views/home/teams.html.erb
| <%= link_to "Back", :back %>

<h1>List of All Teams</h1>

<%= react_component("Team", teams: @teams, stadiums: @stadiums) %>

app/views/home/update_comment.js.erb
document.getElementById("comments").innerHTML = "<%=j render 'comments/index',comments: @comments %>"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FootballApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style type="text/css">
      body, html {
        height: 100%;
      }
      .bg { 
          /* The image used */
          background-image: url(<%= asset_path "background.jpg" %>);

          /* Full height */
          height: 100%; 

          /* Center and scale the image nicely */
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
      }
      .form-signin {
        width: 100%;
        max-width: 330px;
        padding: 15px;
        margin: auto;
      }
      .bg2 {
          color: white;
          /* The image used */
          background-image: url(<%= asset_path "background2.jpg" %>);

          /* Full height */
          height: 100%; 

          /* Center and scale the image nicely */
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
      }
      .bg2 a{color: white;}

    </style>
    <%= javascript_pack_tag 'application' %>
  </head>

  <% if user_signed_in? %>
    <body class="">
      <div class="container">

        <%= link_to "Log out", destroy_user_session_path %>
        |
        <%= link_to "Home", root_path %>
        <%= yield %>
      </div>
    </body>
  <% else %>
    <body>
      <%= yield %>
    </body>
  <% end %>

</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>